#!/bin/bash

if [[ -d "frames" ]]; then
  if [[ $(ls -1 frames | wc -l) -gt "0" ]]; then
    echo "error: frames directory is not empty";
    exit
  fi
else
  mkdir frames
fi

if [[ -f "mandelbrot.mp4" ]]; then
  mv mandelbrot.mp4 mandelbrot.mp4.TEMP
fi

#TODO: use make or cmake like a normal person
if [[ $(stat -c %Y main.cpp) -ge $(stat -c %Y ma) ]]; then
  echo "source file is older than executable; recompiling ...";
  ./compile
fi

echo "generating bmp images" && \
./ma 1920 1080 "frames/frame" --start-frame 0 --num-frames 1000 --anti-alias 5 && \

echo "converting to jpg" && \
mogrify -format jpg frames/* && \

echo "deleting original bmp images" && \
rm frames/frame*.bmp && \

echo "compiling into mp4"
ffmpeg -framerate 30 -i frames/frame%04d.jpg mandelbrot.mp4 && \

#echo "deleting images" && \
#rm -r frames && \

if [[ -f "mandelbrot.mp4.TEMP" ]]; then
  rm mandelbrot.mp4.TEMP
fi
